<?xml version="1.0" encoding="utf-8"?><Database Name="CarRental" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DEV-ANDRE;Initial Catalog=CarRental;Integrated Security=True" SettingsObjectName="ConsoleRentalCar.Properties.Settings" SettingsPropertyName="CarRentalConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.typeCars" Member="typeCars">
    <Type Name="typeCar">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="model" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="licensePlate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="typeCar_rentalRecord" Member="rentalRecords" ThisKey="id" OtherKey="typeCarID" Type="rentalRecord" />
    </Type>
  </Table>
  <Table Name="dbo.rentalRecords" Member="rentalRecords">
    <Type Name="rentalRecord">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="customerName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="dateRented" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dateReturned" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="cost" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="typeCarID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="typeCar_rentalRecord" Member="typeCar" ThisKey="typeCarID" OtherKey="id" Type="typeCar" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.errorInsertData" Member="errorInsertDatas">
    <Type Name="errorInsertData">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="errorLine" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="errorTable" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="errorMessage" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="namefile" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="errorDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>